### ISSUE TITLE
Weird output when model is involved in a function call with an incorrect argument signature

### ISSUE THREAD

**Issue by phantomas1234** [opencobra/MASS-Toolbox#36]
![image](https://cloud.githubusercontent.com/assets/55217/5775224/71eae536-9d77-11e4-8aa9-f98127a5d216.png)

Not sure where the LessEqual comparison would be attempted by Mathematica. This weird output is very annoying and distracts from the actual error message.

**Comment by avsastry** [comment]
This is fixed in branch https://github.com/opencobra/MASS-Toolbox/pull/39
