### ISSUE TITLE
model2sbml should raise an error if MathSBML is not installed

### ISSUE THREAD

**Issue by martamatos** [opencobra/MASS-Toolbox#37]
If MathSBML is not installed, the following error occurs:

![exportsbml2](https://cloud.githubusercontent.com/assets/609864/5776940/32de260c-9d8e-11e4-8085-564bf694a8de.png)

Instead of this error though, it should say that MathSBML is not installed and where it can be obtained.

**Comment by avsastry** [comment]
Fixed the error to be more informative
