### ISSUE TITLE
"String expected at position 2 in Milli <> ToLowerCase[1/Moles]" and "Millimoles/Liters + Millimoles¹/Liters¹ are incompatible units"

### ISSUE THREAD

**Issue by martamatos** [opencobra/MASS-Toolbox#43]
After installing the new MASS Toolbox version (v1 .1.0) with WebInstall, I got the following errors when executing this command: "model = biomodel2model["MODEL1303260018"];":

StringJoin::string: String expected at position 2 in Milli <> ToLowerCase[1/Moles].
Quantity::compat: Millimoles/Liters and Millimoles¹/Liters¹ are incompatible units

When #issue38 was reported there were no problems loading the above model.

**Comment by phantomas1234** [comment]
Ah, this on is similar to the float exponents before. When using the AutomaticUnits package (in the past) something like Millimoles^1/Liters^1 would automatically convert to Millimoles/Liters

**Comment by avsastry** [comment]
This one was because I wasn't too specific on pattern matching when importing units through sbml. I've fixed it in https://github.com/opencobra/MASS-Toolbox/pull/44
