### ISSUE TITLE
updateCustomODE[] duplicates ODEs

### ISSUE THREAD

**Issue by martamatos** [opencobra/MASS-Toolbox#48]
With the model MODEL1303260018, when doing the following:

newODE = model["CustomODE"] /.Toolbox`species["ATP", "cell"][t] -> Toolbox`species["ATP", "cell"];
updateCustomODE[model, newODE];

The ODEs that have changed in newODE are simply duplicated in the model, instead of being substituted.

**Comment by phantomas1234** [comment]
Why should they be substituted? They are not the same. Use `setCustomODE` to overwrite the old ODEs.
