### ISSUE TITLE
apparent error on constructEnzymeModule - naming inhibition reactions

### ISSUE THREAD

**Issue by martamatos** [opencobra/MASS-Toolbox#55]
When having the following enzyme mechanism:

catalyticBranch = {"E_PFK1[c] + f6p[c] <=> E_PFK1[c]&f6p",
   				"E_PFK1[c]&f6p + atp[c] <=> E_PFK1[c]&f6p&atp",
   				"E_PFK1[c]&f6p&atp <=> E_PFK1[c]&fdp&adp",
   				"E_PFK1[c]&fdp&adp <=> E_PFK1[c]&fdp + adp[c]",
   				"E_PFK1[c]&fdp <=> E_PFK1[c] + fdp[c]"};

and constructing the enzyme module with one inhibitor, as follows:

enzymeModel = 
  constructEnzymeModule[Mechanism -> catalyticBranch, 
   Activators -> {}, ActivationSites -> 0, 
   Inhibitors -> {m["pep", "c"]}, InhibitionSites -> 4];

All the inhibition reactions have the same name, which doesn't seem right...

**Comment by avsastry** [comment]
Fixed in https://github.com/opencobra/MASS-Toolbox/pull/58
