### ISSUE TITLE
simulate + plotSimulation results seem wrong in v1.1.7

### ISSUE THREAD

**Issue by martamatos** [opencobra/MASS-Toolbox#61]
The results of simulating a yeast glycolysis model with MASS v1.1.7 do not match the results obtained from Copasi and MASS v1.0.6

Results from MASS v.1.1.7:
![output_mass-1 1 7](https://cloud.githubusercontent.com/assets/609864/11423381/1ae56832-9444-11e5-86c5-6f40bfd3dcac.png)

Results from MASS v1.0.6:
![output_mass-1 0 6](https://cloud.githubusercontent.com/assets/609864/11423384/29e0618e-9444-11e5-902e-2eab4346f92a.png)

**Comment by avsastry** [comment]
Looks like there is an error in the SBML file itself. The initial concentrations are redundantly defined in the file, and my implementation ends up using the one with the error. I will fix this so the results mirror COPASI and the old toolbox code.

**Comment by avsastry** [comment]
Fixed on master branch in 941dda956d8094184c0c9dc599378f11110a718a. This is not in any release as of yet.

**Comment by avsastry** [comment]
Oh also, the units are now in Moles, rather than mM so the axis has to be rescaled when checking this.

**Comment by draeger** [comment]
If concentrations or amounts are redundantly defined, an error should be raised and the user should be asked to choose the right one. Silently selecting something without warning to the user (only motivated to mirror another software's results) is, IMHO, not the best approach.

**Comment by avsastry** [comment]
Makes sense. I'll keep this open and add in a warning message.

**Comment by martamatos** [comment]
With the latest version of the Toolbox (I believe that's what I get when I click "Download ZIP" and the selected branch is the master), I'm getting again different results in Copasi/JWS and in the MASS toolbox. Both with Copasi and JWS I can reproduce the paper's results and with the MASS toolbox the results make no sense: mostly flat lines. 
The model is here http://jjj.biochem.sun.ac.za/models/vaneunen1/simulate/ (also the SBML), all you need to do is a time simulation of 10min and plot the concentration of F16BP.

**Comment by avsastry** [comment]
I am unable to duplicate this error. When I download the SBML from that website, I am able to plot it correctly. Can you run `$ToolboxVersion` to double check your version?

**Comment by martamatos** [comment]
Ok, if I simulate the model in the time interval [0, 10] I also get the "right" result, but if i simulate the model in the interval [0, 100000] I get mostly straight lines:
![vaneunen_ 100000](https://cloud.githubusercontent.com/assets/609864/12420233/b2f28820-bebb-11e5-9216-f65b9fc1be9e.png)

Given the plots I get for the time intervals [0, 1000]:
![vaneunen_ 10000](https://cloud.githubusercontent.com/assets/609864/12420239/b9982ea0-bebb-11e5-87dd-c851c7ef0403.png)

and [0, 10000]:
![vaneunen_ 10000](https://cloud.githubusercontent.com/assets/609864/12420245/c4369c20-bebb-11e5-863a-5f3d2792b08a.png)

I'd suspect the weird results may be related to the integration step... What do you think?

This is the code I'm using:

model = sbml2model[dir <> "vanEunen1.xml"];
{conc, flux} =   simulate[model, {t, 0, tF}];
plotSimulation[conc, PlotFunction -> Plot, PlotRange -> {{0, 10}, {0, 25}}, Legend -> True]

where tF in {1000, 10000, 100000}.

My Toolbox version is "1.1.8".

**Comment by avsastry** [comment]
I think you would need to change your integration steps. Some options that may affect this are MaxStepSize, InterpolationOrder, MaxStepFraction, and StartingStepSize. However, these will take a very long time to compute if you want to simulate from t = 0 to t = 100000. I'd recommend using smaller simulation ranges if you're looking at a small portion, and larger simulation ranges when looking at long time-scales.
