### ISSUE TITLE
issue with importing models edited in copasi

### ISSUE THREAD

**Issue by martamatos** [opencobra/MASS-Toolbox#62]
In Copasi, I used the attached model (in the zip file: Smallbone.xml) to add the following reaction:
acaldt: acetaldehyde{extracellular} -> acetaldehyde{cell}

then exported the model in SBML (level 2 version 4) (attached as Smallbone_acaldt.xml, in the zip file), and tried using it in the MASS toolbox.

I can import it, however it crashes when I simulate it. The code+output is the following:

![bug_import_from_copasi](https://cloud.githubusercontent.com/assets/609864/12977967/632f7c2e-d0ce-11e5-8faa-0d475c73fb8d.png)

The original model (Smallbone.xml) works fine with the MASS toolbox, and both the original and the edited models work fine with Copasi.

[models.zip](https://github.com/opencobra/MASS-Toolbox/files/126455/models.zip)

**Comment by avsastry** [comment]
Looks like the MASS Toolbox IO didn't support custom functions calling other custom functions. This is fixed in the latest commit 340df9d964972cfe931a4a8e5f4545e807c52898
